# Generated by Django 4.2.11 on 2024-03-21 16:41

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "entry_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("cust_ref", models.CharField(blank=True, max_length=8, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "cust_fname",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.RegexValidator("[a-zA-Z]")],
                    ),
                ),
                (
                    "cust_lname",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.RegexValidator("[a-zA-Z]")],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "guest_count",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(8),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "booking_date",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.date(2024, 3, 21)
                            )
                        ]
                    ),
                ),
                (
                    "booking_time",
                    models.TimeField(
                        choices=[
                            (datetime.time(17, 0), "5:00 PM"),
                            (datetime.time(17, 30), "5:30 PM"),
                            (datetime.time(18, 0), "6:00 PM"),
                            (datetime.time(18, 30), "6:30 PM"),
                            (datetime.time(19, 0), "7:00 PM"),
                            (datetime.time(19, 30), "7:30 PM"),
                            (datetime.time(20, 0), "8:00 PM"),
                            (datetime.time(20, 30), "8:30 PM"),
                            (datetime.time(21, 0), "9:00 PM"),
                            (datetime.time(21, 30), "9:30 PM"),
                            (datetime.time(22, 0), "10:00 PM"),
                        ]
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "booking_date",
                    "booking_time",
                    "guest_count",
                    "created_on",
                    "entry_id",
                ],
            },
        ),
    ]
