# Generated by Django 4.2.11 on 2024-03-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['booking_date', 'booking_time', 'guest_count']},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time',
            new_name='booking_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_id_ux',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='reservation',
            name='entry_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
