# Generated by Django 4.2.11 on 2024-03-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_reservation_guest_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['entry_id', 'booking_date', 'booking_time', 'guest_count', 'cancelled']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cancelled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]