# Generated by Django 4.2.11 on 2024-03-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_reservation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='allergies',
        ),
    ]
