# Generated by Django 4.2.11 on 2024-03-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="comments",
            field=models.TextField(blank=True, default="blank"),
            preserve_default=False,
        ),
    ]
