# Generated by Django 4.2.11 on 2024-03-19 23:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_reservation_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="booking_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2024, 3, 19)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="booking_time",
            field=models.TimeField(
                choices=[
                    (datetime.time(17, 0), "5:00 PM"),
                    (datetime.time(17, 30), "5:30 PM"),
                    (datetime.time(18, 0), "6:00 PM"),
                    (datetime.time(18, 30), "6:30 PM"),
                    (datetime.time(19, 0), "7:00 PM"),
                    (datetime.time(19, 30), "7:30 PM"),
                    (datetime.time(20, 0), "8:00 PM"),
                    (datetime.time(20, 30), "8:30 PM"),
                    (datetime.time(21, 0), "9:00 PM"),
                    (datetime.time(21, 30), "9:30 PM"),
                    (datetime.time(22, 0), "10:00 PM"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="cust_fname",
            field=models.CharField(
                max_length=20,
                validators=[django.core.validators.RegexValidator("[a-zA-Z]")],
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="cust_lname",
            field=models.CharField(
                max_length=20,
                validators=[django.core.validators.RegexValidator("[a-zA-Z]")],
            ),
        ),
    ]